const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

try {
  const commit = execSync('git rev-parse --short HEAD', { cwd: path.join(__dirname, '..') }).toString().trim()
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'version.js'), `// Auto-generated by prebuild\nexport const GIT_COMMIT = '${commit}'\n`)
  console.log(`Commit: ${commit}`)
} catch (e) {
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'version.js'), `// Auto-generated by prebuild\nexport const GIT_COMMIT = 'local'\n`)
}
